entrada = input('Type something..')
print('The primitive type of this input is {}'.format(type(entrada)))
print('This input has only spaces? {}'.format(entrada.isspace()))
print('This input is a number? {}'.format(entrada.isnumeric()))
print('This input is alphabetic? {}'.format(entrada.isalpha()))
print('This input is alphanumber? {}'.format(entrada.isalnum()))
print('This input is upper? {}'.format(entrada.isupper()))
print('This input is lower? {}'.format(entrada.islower()))
print('This input is capitalized? {}'.format(entrada.istitle()))